name: chat_bot_ai
description: "Ai Vietravel"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  easy_localization: ^3.0.8
  flutter_riverpod: ^3.2.1
  audioplayers: ^6.5.1
  permission_handler: ^12.0.1
  flutter_sound: ^9.30.0
  rive: ^0.14.3
  flutter_tts: ^4.2.5
  camera: ^0.12.0
  google_mlkit_face_detection: ^0.13.2
  rxdart: ^0.28.0
  dio: ^5.9.1
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.11.1
  retrofit_generator: ^10.2.3


  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/html/
    - assets/avatar/
    - assets/robot/